type: log
#paths:
#{{ range $i, $path := .paths }}
paths:
  - /var/log/nginx/access.log
  - /var/log/nginx/error.log
exclude_files: [".gz$"]
# - {{$path}}
#{{ end }}
#exclude_files: [".gz$"]

processors:
  - add_locale: ~
  - add_fields:
      target: ''
      fields:
        ecs.version: 1.12.0
